# Copyright 2020-present Open Networking Foundation
# SPDX-License-Identifier: Apache-2.0

version: 2.1

jobs:
  build_pipeconf:
    machine:
      image: ubuntu-1604:201903-01
    environment:
      STRATUM_ROOT: /tmp/stratum
    steps:
      - checkout
      - run:
          name: Pull Stratum
          command: git clone https://github.com/stratum/stratum /tmp/stratum
      - run:
          name: Pull Docker images
          command: make pull-images
      - run:
          name: Build pipeconf
          command: make pipeconf

workflows:
  build:
    jobs:
      - build_pipeconf
